name: OnwardBlue
favicon: null
layout_spectrum: 0.26058
typography_spectrum: 0.5886206638533622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1977ba'
    - '#a7a9ac'
    - '#ffffff'
    - '#293b8f'
  brandStrength: 0.8125
  lightness: 0.5478840610012412
  saturation: 0.5625
  rhythmicContrast: 0.2776235695928335
purpose: []
